### ISSUE TITLE
Problem bei IO Start > BIS-Meldedatum

### ISSUE THREAD

**Issue by nscbrandb** [FH-Complete/FHC-Core-DVUH#3]
https://github.com/FH-Complete/FHC-Core-DVUH/blob/7de9a24c4284d53cacc9bc023f33e5ab487837a5/libraries/syncdata/DVUHStudyDataLib.php#L685-L689

e.g. Stichtag 15.11.22, IO Start 01.09.23 (also noch im selben Semester)
DV liefert in diesem Fall den Status "A" aber keine Mobilitätsdaten

Vorschlag: nur IO Daten melden mit von < now(), d.h. die schon begonnen haben
`
$ioResult = $this->_dbModel->execReadOnlyQuery( 
 			"SELECT *
 			FROM bis.tbl_bisio WHERE student_uid=? 
 			AND von < now() AND (bis >= ? OR bis IS NULL) AND von <= ?;", `

**Comment by KarpAlex** [comment]
Sollte nun behoben sein, danke für den Hinweis.

https://github.com/FH-Complete/FHC-Core-DVUH/blob/a8a4973d33b4aecb643825fc4028ddd936ffd0a2/libraries/syncdata/DVUHStudyDataLib.php#L685-L689
